name: "Build Linux"

on:
  workflow_call:

env:
  RUST_TOOLCHAIN: "1.87"

jobs:
  build:
    name: "Build Linux (${{ matrix.this.target }})"
    runs-on: ${{ matrix.this.runner }}
    timeout-minutes: 30

    # Lock Linux to minimum supported version (Ubuntu 18.04 / RHEL 8, glibc
    # 2.28) via a Docker container. PyPa is the Python Packaging Authority, they
    # manage old Linux variants for building Python wheels.
    container: ${{ matrix.this.container }}

    strategy:
      matrix:
        this:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-24.04
            container: quay.io/pypa/manylinux_2_28_x86_64
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-24.04-arm
            container: quay.io/pypa/manylinux_2_28_aarch64

    steps:
      - uses: actions/checkout@v4

      - name: "Install rust"
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.this.target }}

      - name: "Report rust toolchain"
        run: rustup show

      - name: "Build"
        run: cargo build --release --locked --target ${{ matrix.this.target }} -p air

      - name: "Archive"
        run: |
          TARGET=${{ matrix.this.target }}
          ARCHIVE_NAME=air-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/air $ARCHIVE_NAME/air
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          sha256sum $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.this.target }}
          path: |
            *.tar.gz
            *.sha256
