name: "Build Linux"

on:
  workflow_call:

jobs:
  build:
    name: "Build Linux (${{ matrix.this.target }})"
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Lock Linux to minimum supported version (Ubuntu 18.04 / RHEL 8, glibc
    # 2.28). PyPa is the Python Packaging Authority, they manage old Linux
    # variants for building Python wheels.
    container: quay.io/pypa/manylinux_2_28_x86_64

    strategy:
      matrix:
        this:
          - target: x86_64-unknown-linux-gnu
            cross: false
          - target: aarch64-unknown-linux-gnu
            cross: true

    steps:
      - uses: actions/checkout@v4

      - name: "Install cross-compilation tools"
        if: matrix.this.cross
        run: |
          rustup target add ${{ matrix.this.target }}
          python3 -m pip install ziglang cargo-zigbuild

      - name: "Build binary"
        run: |
          if [ "${{ matrix.this.cross }}" = "true" ]; then
            cargo zigbuild --release --locked --target ${{ matrix.this.target }} -p air
          else
            cargo build --release --locked --target ${{ matrix.this.target }} -p air
          fi

      - name: "Archive binary"
        run: |
          TARGET=${{ matrix.this.target }}
          ARCHIVE_NAME=air-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/air $ARCHIVE_NAME/air
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          sha256sum $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.this.target }}
          path: |
            *.tar.gz
            *.sha256
